### ISSUE TITLE
more extensive tests on travis

### ISSUE THREAD

**Issue by jennybc** [mdlincoln/clipr#14]
I am using clipr in [reprex](https://github.com/jennybc/reprex) and had a bit of a struggle getting things set up on travis (surprise ha). But I eventually prevailed.

I learned a couple things that you might be able to use to test clipr more extensively on travis.

Here's my `.travis.yml` and everything beyond the minimum is related to clipr.

https://github.com/jennybc/reprex/blob/master/.travis.yml

First, since xclip is [whitelisted](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise), you can install it and still leave `sudo: false`, so you stay with the container-based infrastructure and caching.

Second, you have to set the DISPLAY environment variable to use the clipboard. Somehow your tests pass (?) but mine certainly did not until I sorted this out.

Thanks again for making clipr! I am happy I can use this for the clipboard stuff 😄.

**Comment by mdlincoln** [comment]
This is great, thank you! The reason my tests were passing is because they didn't really test the clipboard-writing functionality - they just checked that string formats for different objects were written correctly.

Now, this let's travis work well - but will it choke on CRAN without having that DISPLAY variable? Perhaps if we use `Sys.setenv` in the test script, rather than just in `.travis.yml`...

**Comment by mdlincoln** [comment]
Closed with 5fc54ff

**Comment by jennybc** [comment]
CRAN is an interesting question. Because I don't think either xclip or xsel will be there for unix, correct? So I think we have to skip tests in that case. Does clipr already have a function that reports whether the clipboard is even writable / available? That would be handy and then both of us could use that in a test skipper. I guess it would affect lots of tests for you. For me, only a few, because I try to provide the reprex code as file or expression in the tests.

**Comment by mdlincoln** [comment]
That's quite a good idea - and I can see now how that'd be a great function to have exported if one wants to rely on the rest of clipr's functionality! I will write it in and try to get it posted up to CRAN with haste.

FWIW checking the [most recent CRAN results](https://cran.r-project.org/web/checks/check_results_clipr.html) it looks like all the -nix variants on CRAN have either xclip or xsel available... save for R-devel Fedora ¯_(ツ)_/¯

**Comment by jennybc** [comment]
That function would be really helpful. Because I'd also like to check for clipr functionality in my package itself.

And, as the markdown shruggie expert, I think you mean ¯\_(ツ)_/¯.

**Comment by mdlincoln** [comment]
> And, as the markdown shruggie expert, I think you mean ¯\_(ツ)_/¯.

As soon as my comment rendered, I knew you were going to say that 😆

**Comment by mdlincoln** [comment]
I've added the fucntion `is_clipr_available()` which `try`s to write to the clipboard, and returns `TRUE`/`FALSE` based on that attempt. Does that feel sufficient?

**Comment by jennybc** [comment]
I think so. Does it also try to read? I can't imagine when one works and the other doesn't, but maybe it's good to `try` both.

Name-wise, I note that `clipr_available()` or `clipboard_is_available()` reads better inside an `if()`.

**Comment by jennybc** [comment]
> FWIW checking the most recent CRAN results it looks like all the -nix variants on CRAN have either xclip or xsel available... save for R-devel Fedora

Interesting. Just to be clear, you say this because your examples DO run and are effectively testing for the presence of xclip or xsel? This almost seems to good to be true. Because wouldn't that mean CRAN has also done the necessary setup with DISPLAY? I don't have a good sense for how plausible that is.

I can attest that r-hub's linux platforms do not have the clipboard set up 😔.

**Comment by mdlincoln** [comment]
I've renamed to `clipr_available` and also added a check on `read_clip()`, because you never know.

The CRAN situation is befuddling - in part because I've not been as rigorous in my testing as I should have been! What I can see so far:
1. CRAN checks on 0.2.1
   - Examples that attempt `write_clip()` and `read_clip()` pass without complain
   - The tests passed too. But: while those tests called `write_clip()` they did so only to check whether the formatted string that was invisibly returned was correct. They did not actually test to see whether `write_clip()` successfully modified the system clipboard.
2. Travis checks on 0.2.1.9000
   - Examples now fail without xclip/xsel -  so I added `\dontrun{}`
   - The new tests that _do_ evaluate `write_`/`read_clip()` will work if xclip/xsel installed via `.travis.yml`, but also correctly skip (thanks to `clipr_available()`) if the clipboard cannot be accessed.
3. CRAN checks now
   - Examples pass because of `\dontrun{}`
   - Tests apparently fail, even with the checking on `clipr_available()`...

**Comment by mdlincoln** [comment]
Digging in more: so it turns out `clipr_available()` was missing the case in which xclip and/or xsel are installed, but due to `DISPLAY` problems mights still not be available. Trying another configuration now.

**Comment by mdlincoln** [comment]
This now passes CRAN.

**Comment by jennybc** [comment]
🎉 On which OSes does this pass CRAN checks now? What's the status of your examples w/r/t/ dontrun?

I want to submit reprex soon-ish but want you to go first and test the waters 😄.

**Comment by mdlincoln** [comment]
All my examples are now `\dontrun{}` - even though their Debian linux has xclip, it's not set up for headless xclip-ing. This also means that all tests on CRAN linux are skipped - but at least we can evaluate them on Travis linux.

Still waiting on #15, though it looks like that'll be a quick fix.
