### ISSUE TITLE
NA input

### ISSUE THREAD

**Issue by jennybc** [mdlincoln/clipr#23]
A single NA causes an error as input. Two NAs do not.

``` r
clipr::write_clip(NA_character_)
#> Error in writeChar(rendered_content, con = con, eos = eos): invalid 'nchars' argument
clipr::write_clip(c(NA_character_, NA_character_))
clipr::read_clip()
#> [1] NA NA
```

**Comment by mdlincoln** [comment]
This is caused because `nchar(NA_character_)` returns `NA` - an invalid length for `writeChar` to use. The reason that `write_clip(c(NA_character_, NA_character_))` doesn't cause an issue is because, before writing out, `write_clip` collapses the multiple values with the system line break default (`\n` for OS X / Linux), using `paste0`, resulting in the string `NA\nNA`

Given that this is the default for `paste0`, I am going to have `write_clip(NA_character_)` just return the string `NA`.

**Comment by mdlincoln** [comment]
This was also a good impetus to fix handling of `NULL` and empty vectors!

**Comment by jennybc** [comment]
This might inspire me to retweet [this](https://twitter.com/JennyBryan/status/685883713301827584)

> Programming insight of the day 💡:
Anything that can be NULL, NA, or of length zero eventually will be.

**Comment by mdlincoln** [comment]
😂  Indeed! This whole `NA` business made me add a whole bunch of new things to https://github.com/mdlincoln/fuzzr.

**Comment by mdlincoln** [comment]
FYI @jennybc I'll be pushing this to CRAN in a day or two since I know you're trying to get reprex out - let me know if any other clipr edge cases pop up!
