### ISSUE TITLE
clipr::read_path()

### ISSUE THREAD

**Issue by danielsjf** [mdlincoln/clipr#37]
As a feature request, it would be convenient if clipr could also have a function to get the file or folder name of an object.

In Windows, there are ways to do this.
https://www.codeproject.com/Questions/614723/GetFileName-from-Clipboard-Cplusplus

**Comment by mdlincoln** [comment]
Thanks for this idea. Unfortunately, getting the full path rather than just the file name seems entirely platform-dependent. For example, "copying" a file on OS X and then calling `pbpaste` gives the file name but nothing about the larger path. clipr strives to be platform-independent so it can do the same thing regardless of being on Windows, OS X, Red Hat, etc.
