### ISSUE TITLE
Be just as careful with read_clip() as write_clip()

### ISSUE THREAD

**Issue by jennybc** [mdlincoln/clipr#47]
I suspect that `read_clip()` should have the same safeguards vis-a-vis CRAN-proofing as `write_clip()`. So it should not even think about touching the clipboard in a non-interactive session, unless CLIPR_ALLOW is TRUE.

**Comment by mdlincoln** [comment]
Closed with 17bdae67de162eeeb65419829fe6d450fac202e4

**Comment by mdlincoln** [comment]
@jennybc Give this a spin with your latest! FYI I noticed a glaring issue in the docs for `clipr_available`, which at one point stated that the envvar being checked was `CLIPBOARD_AVAILABLE` rather than `CLIPR_ALLOW` 🙊 😓 It looks like this was at one point written into the code for reprex - things are now passing revdepchecks, and it looks like you no longer call that in current reprex code, but I just wanted to double-check.
