### ISSUE TITLE
Use native (C) apis

### ISSUE THREAD

**Issue by hadley** [mdlincoln/clipr#8]
This package would be even more awesome (and more elegant) if instead of using command-line tools, you used the native API on each platform. This is probably a bit fiddly, but I but there are three people in the R community who each know how to do it on one platform.

cc @kevinushey, hint hint...

**Comment by hadley** [comment]
(Another approach would be see if there's a similar package for python or ruby and modify the code to work with R instead)

**Comment by lmmx** [comment]
Sounds like a good idea, it might well be faster - but a more complicated package.

A [GitHub search](https://github.com/search?l=C&q=clipboard&ref=opensearch&type=Repositories) brings up:
- [`trezker/clipboard`](https://github.com/trezker/clipboard), "aiming for cross-platform" but Linux-only (no license given)
- [`fumiyas/gclip`](https://github.com/fumiyas/gclip/blob/master/gclip.c), GTK (GNOME) interface (Linux), MIT
- [`RoxasShadow/reginaldo`](https://github.com/RoxasShadow/reginaldo), "aiming for cross-platform" but Windows-only (mainly C, some Ruby), GPL
- [`roryyorke/picellif`](https://github.com/roryyorke/picellif), tested on Win64 only, "may not work with older versions of Windows", MIT
- [`ivartj/wclip`](https://github.com/ivartj/wclip), Windows interface seemingly 32-bit only(?), no license given
- [`eel3/rtcb`](https://github.com/eel3/rtcb), Win32/64, XP or later, [permissive] NYSL license

( ... and [this](https://www.daniweb.com/software-development/c/code/217173/transfer-data-tofrom-the-windows-clipboard) is some miscellaneous C for clipboard operations on Windows, [via a StackOverflow question about OS-independent clipboard operations which wasn't really resolved](http://stackoverflow.com/questions/2270243/os-independent-clipboard-copy-paste-text-in-c#comment2232376_2270313) ... )

RE: the 2nd approach, Python and Ruby-wise:
- [Pyperclip](https://github.com/asweigart/pyperclip/blob/master/pyperclip/__init__.py) (Python) appears to use a C API for Windows, but pipes to command-line tools and Qt/Gtk otherwise
- [`janlelis/clipboard`](https://github.com/janlelis/clipboard) (Ruby) appears to pipe to command-line tools
- [`kiyoka/pastehub`](https://github.com/kiyoka/pastehub) (Ruby), native clipboard used on Windows & Mac (not Linux), BSD-licensed
- [`mvidner/ctoolu`](https://github.com/mvidner/ctoolu) (Ruby), "universal" (cross-platform?) clipboard manager in Ruby, doesn't appear to pipe to command-line tools, GPL-licensed, uses Gtk2 and D-BUS (via other Ruby modules)
